// SPDX-License-Identifier: AGPL-3.0-or-later

//! Server functions for the chat WebSocket system.
//!
//! Provides WebSocket configuration (token, user_id, workspace_id) for the
//! client-side WebSocket context provider. The token is a short-lived JWT
//! matching the format generated by `apps/server/src/routes/auth.rs`
//! `GET /api/v1/auth/websocket-token`.

use leptos::prelude::*;
use serde::{Deserialize, Serialize};

/// WebSocket configuration returned to the client for establishing a connection.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WebSocketConfig {
    pub token: String,
    pub user_id: String,
    pub workspace_id: String,
}

/// Obtain a WebSocket authentication token for the current user.
///
/// Generates a short-lived JWT (15 minutes) signed with the app's JWT secret,
/// matching the token format produced by `GET /api/v1/auth/websocket-token`.
/// The client uses this token to authenticate the WebSocket upgrade request.
#[server(prefix = "/leptos-api")]
pub async fn get_websocket_config() -> Result<WebSocketConfig, ServerFnError> {
    let auth = super::extract_auth().await?;
    let ctx = super::extract_context()?;
    let workspace_id = super::workspace_id(&auth)?.to_string();

    let mut extra = std::collections::HashMap::new();
    extra.insert("user_id".into(), serde_json::json!(auth.user_id));
    extra.insert("email".into(), serde_json::json!(auth.email));
    extra.insert("name".into(), serde_json::json!(auth.name));
    extra.insert("roles".into(), serde_json::json!(auth.roles));

    // Short-lived token (15 minutes) — matches apps/server/src/routes/auth.rs
    let token = kyomi_auth::jwt::create_access_token_str(
        &auth.user_id,
        &ctx.config.jwt_secret,
        15,
        extra,
    )
    .map_err(|e| ServerFnError::new(format!("Failed to create WebSocket token: {e}")))?;

    Ok(WebSocketConfig {
        token,
        user_id: auth.user_id,
        workspace_id,
    })
}
