// SPDX-License-Identifier: AGPL-3.0-or-later

//! ChatSession model — maps to the `chat_sessions` table.
//!
//! Matches Python's `ChatSession` model in `database/models.py`.
//! Session IDs are UUIDs stored as `String` (VARCHAR 50).

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::enums::SessionType;

/// A chat session record from the `chat_sessions` table.
#[derive(Debug, Clone, sqlx::FromRow, Serialize, Deserialize)]
pub struct ChatSession {
    /// Primary key — UUID string.
    pub session_id: String,

    /// FK to users table — the session owner.
    pub user_id: String,

    /// FK to workspaces table — workspace isolation.
    pub workspace_id: String,

    /// Display title (auto-generated by AI after first message, nullable).
    pub title: Option<String>,

    /// LLM model used for this session (e.g. "claude-haiku-4-5-20251001").
    pub model: Option<String>,

    /// Session type: "chat" or "dashboard_copilot".
    /// Server default is 'chat'.
    pub session_type: SessionType,

    /// Whether this session is shared with workspace members.
    /// Server default is false.
    #[sqlx(default)]
    pub shared: bool,

    /// When the session was shared (nullable).
    pub shared_at: Option<DateTime<Utc>>,

    /// Record creation timestamp.
    pub created_at: DateTime<Utc>,

    /// Last modification timestamp.
    pub updated_at: DateTime<Utc>,

    /// Session configuration (JSON blob — compaction info, iteration counter, etc.).
    pub config: Option<serde_json::Value>,

    /// Messaging platform type (e.g. "slack", "teams"). NULL for web sessions.
    pub platform_type: Option<String>,

    /// Platform-specific thread key (e.g. Slack "channel:ts"). NULL for web sessions.
    pub platform_thread_key: Option<String>,
}
