// SPDX-License-Identifier: AGPL-3.0-or-later

//! Typst-based PDF generation.
//!
//! Compiles a Typst document string (with image references) to PDF bytes.
//! Uses `typst-as-lib` for compilation and `typst-pdf` for export.

use std::collections::HashMap;
use typst::layout::PagedDocument;
use typst_as_lib::TypstEngine;

/// Generate a PDF from a Typst document string and a set of named images.
///
/// Images are referenced in the Typst source as `#image("chart_0.png")` etc.
/// The `images` map provides the PNG bytes for each filename.
///
/// Returns raw PDF bytes.
pub fn generate_pdf(
    typst_source: &str,
    images: &HashMap<String, Vec<u8>>,
) -> Result<Vec<u8>, String> {
    // Build image file entries for the static file resolver
    let image_entries: Vec<(&str, &[u8])> = images
        .iter()
        .map(|(name, bytes)| (name.as_str(), bytes.as_slice()))
        .collect();

    // Build the Typst engine with embedded fonts and image resolver
    let mut builder = TypstEngine::builder()
        .main_file(typst_source);

    if !image_entries.is_empty() {
        builder = builder.with_static_file_resolver(image_entries);
    }

    let engine = builder.build();

    // Compile the document
    let warned = engine.compile::<PagedDocument>();
    let doc = warned.output.map_err(|e| format!("Typst compilation failed: {e}"))?;

    // Log any warnings (non-fatal)
    for warning in &warned.warnings {
        tracing::warn!(message = %warning.message, "Typst warning");
    }

    // Export to PDF
    let options = typst_pdf::PdfOptions::default();
    let pdf_bytes = typst_pdf::pdf(&doc, &options)
        .map_err(|errors| {
            let msgs: Vec<String> = errors.iter().map(|e| format!("{:?}", e)).collect();
            format!("PDF export failed: {}", msgs.join("; "))
        })?;

    Ok(pdf_bytes.into())
}

/// Build a complete Typst document with page setup, styling, and body content.
///
/// This wraps the body content with consistent page layout, fonts,
/// heading styles, and footer.
pub fn wrap_document(title: &str, body: &str) -> String {
    let escaped_title = typst_escape(title);
    format!(
        r##"#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2.5cm, left: 1.5cm, right: 1.5cm),
  footer: context {{
    set text(8pt, fill: rgb("#9ca3af"))
    counter(page).display("1 / 1", both: true)
    h(1fr)
    [Generated by kyomi.ai]
  }},
)

#set text(11pt, font: "New Computer Modern")
#set par(leading: 0.8em, spacing: 1.2em)

#set heading(numbering: none)
#show heading.where(level: 1): it => {{
  set text(22pt, weight: "bold", fill: rgb("#111827"))
  block(below: 8pt, it.body)
  line(length: 100%, stroke: 2pt + rgb("#e5e7eb"))
  v(6pt)
}}
#show heading.where(level: 2): set text(16pt, weight: "semibold", fill: rgb("#1f2937"))
#show heading.where(level: 3): set text(13pt, weight: "semibold", fill: rgb("#374151"))

#show link: set text(fill: rgb("#2563eb"))

= {escaped_title}

{body}
"##
    )
}

/// Escape special Typst characters in text content.
///
/// Typst uses `*`, `_`, `#`, etc. as markup. We need to escape them
/// when inserting raw text that should be displayed literally.
pub fn typst_escape(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '#' | '*' | '_' | '`' | '@' | '<' | '>' | '$' | '~' | '\\' => {
                result.push('\\');
                result.push(c);
            }
            _ => result.push(c),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_pdf() {
        let source = r#"
#set page(paper: "a4")
#set text(11pt)
= Hello World
This is a test document.
"#;
        let images = HashMap::new();
        let result = generate_pdf(source, &images);
        assert!(result.is_ok(), "PDF generation failed: {:?}", result.err());
        let pdf = result.unwrap();
        // PDF magic bytes
        assert_eq!(&pdf[0..5], b"%PDF-");
        assert!(pdf.len() > 100);
    }

    #[test]
    fn wrap_document_includes_title() {
        let doc = wrap_document("My Dashboard", "Some content here");
        assert!(doc.contains("My Dashboard"));
        assert!(doc.contains("Some content here"));
        assert!(doc.contains("kyomi.ai"));
    }

    #[test]
    fn typst_escape_special_chars() {
        assert_eq!(typst_escape("Revenue & *Costs*"), "Revenue & \\*Costs\\*");
        assert_eq!(typst_escape("#heading"), "\\#heading");
        assert_eq!(typst_escape("$100"), "\\$100");
        assert_eq!(typst_escape("normal text"), "normal text");
    }

    #[test]
    fn full_document_generates_pdf() {
        let body = "== Section 1\nSome paragraph text.\n\n== Section 2\nMore text here.";
        let doc = wrap_document("Test Dashboard", body);
        let result = generate_pdf(&doc, &HashMap::new());
        assert!(result.is_ok(), "Full doc PDF failed: {:?}", result.err());
    }
}
