// SPDX-License-Identifier: AGPL-3.0-or-later

//! Typst-based PDF generation.
//!
//! Compiles a Typst document string (with image references) to PDF bytes.
//! Uses `typst-as-lib` for compilation and `typst-pdf` for export.

use std::collections::HashMap;
use typst::layout::PagedDocument;
use typst_as_lib::{typst_kit_options::TypstKitFontOptions, TypstEngine};

/// Generate a PDF from a Typst document string and a set of named images.
///
/// Images are referenced in the Typst source as `#image("chart_0.png")` etc.
/// The `images` map provides the PNG bytes for each filename.
///
/// Returns raw PDF bytes.
pub fn generate_pdf(
    typst_source: &str,
    images: &HashMap<String, Vec<u8>>,
) -> Result<Vec<u8>, String> {
    // Build image file entries for the static file resolver
    let image_entries: Vec<(&str, &[u8])> = images
        .iter()
        .map(|(name, bytes)| (name.as_str(), bytes.as_slice()))
        .collect();

    // Build the Typst engine with embedded fonts and image resolver.
    // search_fonts_with() is required — without it no fonts are loaded and
    // the PDF renders with no text.
    let mut builder = TypstEngine::builder()
        .main_file(typst_source)
        .search_fonts_with(TypstKitFontOptions::new());

    if !image_entries.is_empty() {
        builder = builder.with_static_file_resolver(image_entries);
    }

    let engine = builder.build();

    // Compile the document
    let warned = engine.compile::<PagedDocument>();
    let doc = warned.output.map_err(|e| format!("Typst compilation failed: {e}"))?;

    // Log any warnings (non-fatal)
    for warning in &warned.warnings {
        tracing::warn!(message = %warning.message, "Typst warning");
    }

    // Export to PDF
    let options = typst_pdf::PdfOptions::default();
    let pdf_bytes = typst_pdf::pdf(&doc, &options)
        .map_err(|errors| {
            let msgs: Vec<String> = errors.iter().map(|e| format!("{:?}", e)).collect();
            format!("PDF export failed: {}", msgs.join("; "))
        })?;

    Ok(pdf_bytes)
}

/// Build a complete Typst document with page setup, styling, and body content.
///
/// This wraps the body content with consistent page layout, fonts,
/// heading styles, and footer.
pub fn wrap_document(title: &str, body: &str) -> String {
    let escaped_title = typst_escape(title);
    format!(
        r##"#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  footer: context {{
    line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))
    v(4pt)
    set text(8pt, fill: rgb("#9ca3af"), font: "Open Sans")
    [Generated by kyomi.ai]
    h(1fr)
    counter(page).display()
  }},
)

#set text(10.5pt, font: "Open Sans", fill: rgb("#374151"))
#set par(leading: 0.65em, spacing: 1em)

#set heading(numbering: none)
#show heading.where(level: 1): it => {{
  v(4pt)
  set text(20pt, weight: "bold", fill: rgb("#111827"), font: "Open Sans")
  it.body
  v(2pt)
  line(length: 100%, stroke: 1.5pt + rgb("#e5e7eb"))
  v(8pt)
}}
#show heading.where(level: 2): it => {{
  v(8pt)
  set text(14pt, weight: "semibold", fill: rgb("#1f2937"), font: "Open Sans")
  it.body
  v(4pt)
}}
#show heading.where(level: 3): it => {{
  v(4pt)
  set text(12pt, weight: "semibold", fill: rgb("#374151"), font: "Open Sans")
  it.body
  v(2pt)
}}

#show link: set text(fill: rgb("#2563eb"))

= {escaped_title}

{body}
"##
    )
}

/// Escape special Typst characters in text content.
///
/// Typst uses `*`, `_`, `#`, etc. as markup. We need to escape them
/// when inserting raw text that should be displayed literally.
pub fn typst_escape(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '#' | '*' | '_' | '`' | '@' | '<' | '>' | '$' | '~' | '\\' => {
                result.push('\\');
                result.push(c);
            }
            _ => result.push(c),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    /// Write PDF bytes to a temp file, extract text with pdftotext, return the text.
    fn pdf_to_text(pdf: &[u8], label: &str) -> String {
        let path = format!("/tmp/kyomi_test_{label}.pdf");
        std::fs::write(&path, pdf).expect("failed to write pdf");
        let out = Command::new("pdftotext")
            .args([&path, "-"])
            .output()
            .expect("pdftotext not found — install poppler-utils");
        assert!(
            out.status.success(),
            "pdftotext failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8_lossy(&out.stdout).to_string()
    }

    #[test]
    fn typst_escape_special_chars() {
        assert_eq!(typst_escape("Revenue & *Costs*"), "Revenue & \\*Costs\\*");
        assert_eq!(typst_escape("#heading"), "\\#heading");
        assert_eq!(typst_escape("$100"), "\\$100");
        assert_eq!(typst_escape("normal text"), "normal text");
    }

    #[test]
    fn simple_document_renders_text() {
        let source = r#"
#set page(paper: "a4")
#set text(11pt)
= Hello World
This is a test document with some content.
"#;
        let pdf = generate_pdf(source, &HashMap::new())
            .expect("PDF generation failed");
        let text = pdf_to_text(&pdf, "simple");
        assert!(text.contains("Hello World"), "title missing from PDF text: {text}");
        assert!(text.contains("test document"), "body missing from PDF text: {text}");
    }

    #[test]
    fn wrap_document_renders_title_and_body() {
        let body = "Some paragraph text here.\n\nA second paragraph.";
        let doc = wrap_document("Test Dashboard", body);
        let pdf = generate_pdf(&doc, &HashMap::new())
            .expect("PDF generation failed");
        let text = pdf_to_text(&pdf, "wrapped");
        assert!(text.contains("Test Dashboard"), "title missing: {text}");
        assert!(text.contains("Some paragraph text"), "body missing: {text}");
        assert!(text.contains("kyomi.ai"), "footer missing: {text}");
    }

    #[test]
    fn dashboard_pdf_renders_all_content() {
        use crate::markdown_to_typst::{markdown_to_typst, render_metric_typst, render_data_table_typst};

        let metric1 = render_metric_typst("Total Revenue", "$1.45M", Some(("20.3%", true)));
        let metric2 = render_metric_typst("Active Users", "12,847", Some(("3.1%", false)));

        let table = render_data_table_typst(
            "Top Regions",
            &["Region".into(), "Revenue".into(), "Growth".into()],
            &[
                vec!["North America".into(), "$620K".into(), "+15%".into()],
                vec!["Europe".into(), "$410K".into(), "+22%".into()],
                vec!["Asia Pacific".into(), "$280K".into(), "+31%".into()],
            ],
            3,
            50,
        );

        let markdown = format!(
            "# Monthly Revenue Report\n\n{metric1}\n\n{metric2}\n\n\
            ## Highlights\n\n\
            - Enterprise deals closed: **12**\n\
            - New customers acquired: **47**\n\
            - Monthly churn rate: `1.2%`\n\n\
            {table}\n\n\
            ## Action Items\n\n\
            1. Expand APAC sales team by Q3\n\
            2. Launch mid-market pricing tier\n\n\
            ---\n\n\
            *Report generated by Kyomi.*\n"
        );

        let typst_body = markdown_to_typst(&markdown);
        let typst_doc = wrap_document("Monthly Revenue Report", &typst_body);
        std::fs::write("/tmp/kyomi_test_dashboard.typ", &typst_doc).unwrap();

        let pdf = generate_pdf(&typst_doc, &HashMap::new())
            .expect("PDF generation failed");
        let text = pdf_to_text(&pdf, "dashboard");

        // Title
        assert!(text.contains("Monthly Revenue Report"), "title missing: {text}");
        // Metric cards
        assert!(text.contains("Total Revenue"), "metric label missing: {text}");
        assert!(text.contains("1.45M"), "metric value missing: {text}");
        assert!(text.contains("20.3%"), "metric trend missing: {text}");
        assert!(text.contains("Active Users"), "metric 2 label missing: {text}");
        assert!(text.contains("12,847"), "metric 2 value missing: {text}");
        // Table
        assert!(text.contains("Top Regions"), "table title missing: {text}");
        assert!(text.contains("North America"), "table row missing: {text}");
        assert!(text.contains("Asia Pacific"), "table row missing: {text}");
        // List
        assert!(text.contains("Enterprise deals closed"), "list item missing: {text}");
        // Numbered list
        assert!(text.contains("Expand APAC"), "numbered list missing: {text}");
        // Footer
        assert!(text.contains("kyomi.ai"), "footer missing: {text}");
    }

    #[test]
    fn dashboard_pdf_with_chart() {
        use crate::chartml_factory::render_chart_to_png_sync;
        use crate::markdown_to_typst::{markdown_to_typst, render_metric_typst};

        // ChartML bar chart with inline data (no datasource needed)
        let chart_yaml = r##"
type: chart
version: 1
title: "Monthly Revenue"
data:
  provider: inline
  rows:
    - month: "Jan"
      revenue: 42000
    - month: "Feb"
      revenue: 51000
    - month: "Mar"
      revenue: 48000
    - month: "Apr"
      revenue: 63000
    - month: "May"
      revenue: 71000
    - month: "Jun"
      revenue: 68000
visualize:
  type: bar
  columns: month
  rows: revenue
  axes:
    rows:
      label: "Revenue ($)"
      format: "$,.0f"
"##;

        // Render chart to PNG
        let chart_png = render_chart_to_png_sync(chart_yaml, 700, 380, 144, None)
            .expect("Chart rendering failed");
        assert!(!chart_png.is_empty(), "chart PNG is empty");

        // Store PNG for Typst to embed
        let mut images = HashMap::new();
        images.insert("chart_0.png".to_string(), chart_png);

        let metric = render_metric_typst("Total Revenue", "$343K", Some(("18.2%", true)));

        let markdown = format!(
            "# Revenue Dashboard\n\n\
            {metric}\n\n\
            ## Monthly Revenue\n\n\
            #image(\"chart_0.png\", width: 100%)\n\n\
            ## Summary\n\n\
            Revenue grew consistently through H1, with June showing a slight dip from May's peak.\n"
        );

        let typst_body = markdown_to_typst(&markdown);
        let typst_doc = wrap_document("Revenue Dashboard", &typst_body);
        std::fs::write("/tmp/kyomi_test_chart.typ", &typst_doc).unwrap();

        let pdf = generate_pdf(&typst_doc, &images).expect("PDF generation failed");
        let text = pdf_to_text(&pdf, "chart");

        assert!(text.contains("Revenue Dashboard"), "title missing: {text}");
        assert!(text.contains("Total Revenue"), "metric missing: {text}");
        assert!(text.contains("343K"), "metric value missing: {text}");
        assert!(text.contains("Monthly Revenue"), "section heading missing: {text}");
        assert!(text.contains("Revenue grew"), "body text missing: {text}");
        assert!(text.contains("kyomi.ai"), "footer missing: {text}");
    }
}
